
animal (X) :- mammal (X), X is 199.
animal (X) :- mammal (X), X is 198.
animal (X) :- mammal (X), X is 197.
animal (X) :- mammal (X), X is 196.
animal (X) :- mammal (X), X is 195.
animal (X) :- mammal (X), X is 194.
animal (X) :- mammal (X), X is 193.
animal (X) :- mammal (X), X is 192.
animal (X) :- mammal (X), X is 191.
animal (X) :- mammal (X), X is 190.
animal (X) :- mammal (X), X is 189.
animal (X) :- mammal (X), X is 188.
animal (X) :- mammal (X), X is 187.
animal (X) :- mammal (X), X is 186.
animal (X) :- mammal (X), X is 185.
animal (X) :- mammal (X), X is 184.
animal (X) :- mammal (X), X is 183.
animal (X) :- mammal (X), X is 182.
animal (X) :- mammal (X), X is 181.
animal (X) :- mammal (X), X is 180.
animal (X) :- mammal (X), X is 179.
animal (X) :- mammal (X), X is 178.
animal (X) :- mammal (X), X is 177.
animal (X) :- mammal (X), X is 176.
animal (X) :- mammal (X), X is 175.
animal (X) :- mammal (X), X is 174.
animal (X) :- mammal (X), X is 173.
animal (X) :- mammal (X), X is 172.
animal (X) :- mammal (X), X is 171.
animal (X) :- mammal (X), X is 170.
animal (X) :- mammal (X), X is 169.
animal (X) :- mammal (X), X is 168.
animal (X) :- mammal (X), X is 167.
animal (X) :- mammal (X), X is 166.
animal (X) :- mammal (X), X is 165.
animal (X) :- mammal (X), X is 164.
animal (X) :- mammal (X), X is 163.
animal (X) :- mammal (X), X is 162.
animal (X) :- mammal (X), X is 161.
animal (X) :- mammal (X), X is 160.
animal (X) :- mammal (X), X is 159.
animal (X) :- mammal (X), X is 158.
animal (X) :- mammal (X), X is 157.
animal (X) :- mammal (X), X is 156.
animal (X) :- mammal (X), X is 155.
animal (X) :- mammal (X), X is 154.
animal (X) :- mammal (X), X is 153.
animal (X) :- mammal (X), X is 152.
animal (X) :- mammal (X), X is 151.
animal (X) :- mammal (X), X is 150.
animal (X) :- mammal (X), X is 149.
animal (X) :- mammal (X), X is 148.
animal (X) :- mammal (X), X is 147.
animal (X) :- mammal (X), X is 146.
animal (X) :- mammal (X), X is 145.
animal (X) :- mammal (X), X is 144.
animal (X) :- mammal (X), X is 143.
animal (X) :- mammal (X), X is 142.
animal (X) :- mammal (X), X is 141.
animal (X) :- mammal (X), X is 140.
animal (X) :- mammal (X), X is 139.
animal (X) :- mammal (X), X is 138.
animal (X) :- mammal (X), X is 137.
animal (X) :- mammal (X), X is 136.
animal (X) :- mammal (X), X is 135.
animal (X) :- mammal (X), X is 134.
animal (X) :- mammal (X), X is 133.
animal (X) :- mammal (X), X is 132.
animal (X) :- mammal (X), X is 131.
animal (X) :- mammal (X), X is 130.
animal (X) :- mammal (X), X is 129.
animal (X) :- mammal (X), X is 128.
animal (X) :- mammal (X), X is 127.
animal (X) :- mammal (X), X is 126.
animal (X) :- mammal (X), X is 125.
animal (X) :- mammal (X), X is 124.
animal (X) :- mammal (X), X is 123.
animal (X) :- mammal (X), X is 122.
animal (X) :- mammal (X), X is 121.
animal (X) :- mammal (X), X is 120.
animal (X) :- mammal (X), X is 119.
animal (X) :- mammal (X), X is 118.
animal (X) :- mammal (X), X is 117.
animal (X) :- mammal (X), X is 116.
animal (X) :- mammal (X), X is 115.
animal (X) :- mammal (X), X is 114.
animal (X) :- mammal (X), X is 113.
animal (X) :- mammal (X), X is 112.
animal (X) :- mammal (X), X is 111.
animal (X) :- mammal (X), X is 110.
animal (X) :- mammal (X), X is 109.
animal (X) :- mammal (X), X is 108.
animal (X) :- mammal (X), X is 107.
animal (X) :- mammal (X), X is 106.
animal (X) :- mammal (X), X is 105.
animal (X) :- mammal (X), X is 104.
animal (X) :- mammal (X), X is 103.
animal (X) :- mammal (X), X is 102.
animal (X) :- mammal (X), X is 101.
animal (X) :- mammal (X), X is 100.
animal (X) :- mammal (X), X is 99.
animal (X) :- mammal (X), X is 98.
animal (X) :- mammal (X), X is 97.
animal (X) :- mammal (X), X is 96.
animal (X) :- mammal (X), X is 95.
animal (X) :- mammal (X), X is 94.
animal (X) :- mammal (X), X is 93.
animal (X) :- mammal (X), X is 92.
animal (X) :- mammal (X), X is 91.
animal (X) :- mammal (X), X is 90.
animal (X) :- mammal (X), X is 89.
animal (X) :- mammal (X), X is 88.
animal (X) :- mammal (X), X is 87.
animal (X) :- mammal (X), X is 86.
animal (X) :- mammal (X), X is 85.
animal (X) :- mammal (X), X is 84.
animal (X) :- mammal (X), X is 83.
animal (X) :- mammal (X), X is 82.
animal (X) :- mammal (X), X is 81.
animal (X) :- mammal (X), X is 80.
animal (X) :- mammal (X), X is 79.
animal (X) :- mammal (X), X is 78.
animal (X) :- mammal (X), X is 77.
animal (X) :- mammal (X), X is 76.
animal (X) :- mammal (X), X is 75.
animal (X) :- mammal (X), X is 74.
animal (X) :- mammal (X), X is 73.
animal (X) :- mammal (X), X is 72.
animal (X) :- mammal (X), X is 71.
animal (X) :- mammal (X), X is 70.
animal (X) :- mammal (X), X is 69.
animal (X) :- mammal (X), X is 68.
animal (X) :- mammal (X), X is 67.
animal (X) :- mammal (X), X is 66.
animal (X) :- mammal (X), X is 65.
animal (X) :- mammal (X), X is 64.
animal (X) :- mammal (X), X is 63.
animal (X) :- mammal (X), X is 62.
animal (X) :- mammal (X), X is 61.
animal (X) :- mammal (X), X is 60.
animal (X) :- mammal (X), X is 59.
animal (X) :- mammal (X), X is 58.
animal (X) :- mammal (X), X is 57.
animal (X) :- mammal (X), X is 56.
animal (X) :- mammal (X), X is 55.
animal (X) :- mammal (X), X is 54.
animal (X) :- mammal (X), X is 53.
animal (X) :- mammal (X), X is 52.
animal (X) :- mammal (X), X is 51.
animal (X) :- mammal (X), X is 50.
animal (X) :- mammal (X), X is 49.
animal (X) :- mammal (X), X is 48.
animal (X) :- mammal (X), X is 47.
animal (X) :- mammal (X), X is 46.
animal (X) :- mammal (X), X is 45.
animal (X) :- mammal (X), X is 44.
animal (X) :- mammal (X), X is 43.
animal (X) :- mammal (X), X is 42.
animal (X) :- mammal (X), X is 41.
animal (X) :- mammal (X), X is 40.
animal (X) :- mammal (X), X is 39.
animal (X) :- mammal (X), X is 38.
animal (X) :- mammal (X), X is 37.
animal (X) :- mammal (X), X is 36.
animal (X) :- mammal (X), X is 35.
animal (X) :- mammal (X), X is 34.
animal (X) :- mammal (X), X is 33.
animal (X) :- mammal (X), X is 32.
animal (X) :- mammal (X), X is 31.
animal (X) :- mammal (X), X is 30.
animal (X) :- mammal (X), X is 29.
animal (X) :- mammal (X), X is 28.
animal (X) :- mammal (X), X is 27.
animal (X) :- mammal (X), X is 26.
animal (X) :- mammal (X), X is 25.
animal (X) :- mammal (X), X is 24.
animal (X) :- mammal (X), X is 23.
animal (X) :- mammal (X), X is 22.
animal (X) :- mammal (X), X is 21.
animal (X) :- mammal (X), X is 20.
animal (X) :- mammal (X), X is 19.
animal (X) :- mammal (X), X is 18.
animal (X) :- mammal (X), X is 17.
animal (X) :- mammal (X), X is 16.
animal (X) :- mammal (X), X is 15.
animal (X) :- mammal (X), X is 14.
animal (X) :- mammal (X), X is 13.
animal (X) :- mammal (X), X is 12.
animal (X) :- mammal (X), X is 11.
animal (X) :- mammal (X), X is 10.
animal (X) :- mammal (X), X is 9.
animal (X) :- mammal (X), X is 8.
animal (X) :- mammal (X), X is 7.
animal (X) :- mammal (X), X is 6.
animal (X) :- mammal (X), X is 5.
animal (X) :- mammal (X), X is 4.
animal (X) :- mammal (X), X is 3.
animal (X) :- mammal (X), X is 2.
animal (X) :- mammal (X), X is 1.
animal (X) :- mammal (X), X is 0.

mammal (20).