package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:29 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.Loader
  extends com.svincent.moksa.PrologLoader
{
  public com.svincent.moksa.prolog.parser_prolog.Loader ()
  {
  }
  
  public void load (com.svincent.moksa.PrologEngine engine)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.PrologFactory factory;
    factory = engine.getFactory();
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.read_term_1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.read_term_2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.tokenize_prolog_term_3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4_alt2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4_alt3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.make_unique_variable_token_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.make_unique_variable_token_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.make_unique_variable_token_4_alt2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_2_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt5());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_arg_list_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_args_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_args_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt6());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt7());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt8());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt9());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt10());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_exp_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_exp_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt11());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt12());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt13());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt14());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_infix_subpriority_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_infix_subpriority_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_infix_subpriority_4_alt2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_prefix_subpriority_3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_prefix_subpriority_3_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_postfix_subpriority_3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.calculate_prolog_postfix_subpriority_3_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt15());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_list_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_list_4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_list_4_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_list_4_alt2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.operator_no_comma_1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.operator_no_comma_1_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.operator_1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt1());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt2());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt3());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt4());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt5());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt6());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt7());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt8());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt9());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt10());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt11());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt12());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt13());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt14());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt15());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt16());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt17());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt18());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt19());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt20());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt21());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt22());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt23());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt24());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt25());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt26());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt27());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt28());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt29());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt30());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt31());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt32());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt33());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt34());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt35());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt36());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt37());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt38());
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.parser_prolog.current_op_3_alt39());
  }
  
}
