package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:17 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.make_unique_variable_token_4_alt2
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.make_unique_variable_token_4_alt2 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_2;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg Name
    //  --- Name
    var_0 = factory.makeVariable((java.lang.String)"Name");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)var_0))
      return wam.Fail;
    //  *** test arg [X | MoreVars]
    //  --- X
    var_1 = factory.makeVariable((java.lang.String)"X");
    //  --- MoreVars
    var_2 = factory.makeVariable((java.lang.String)"MoreVars");
    //  --- [X | MoreVars]
    compound_3 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_2});
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)compound_3))
      return wam.Fail;
    //  *** test arg VarToken
    //  --- VarToken
    var_4 = factory.makeVariable((java.lang.String)"VarToken");
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)var_4))
      return wam.Fail;
    //  *** test arg [X | NewVars]
    //  --- NewVars
    var_5 = factory.makeVariable((java.lang.String)"NewVars");
    //  --- [X | NewVars]
    compound_6 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_5});
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)compound_6))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- make_unique_variable_token(Name, MoreVars, VarToken, NewVars)
    compound_7 = factory.makeCompoundTerm((java.lang.String)"make_unique_variable_token", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_2, var_4, var_5});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_7, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "make_unique_variable_token/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_8;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_2;
    //  --- Name
    var_0 = factory.makeVariable((java.lang.String)"Name");
    //  --- X
    var_1 = factory.makeVariable((java.lang.String)"X");
    //  --- MoreVars
    var_2 = factory.makeVariable((java.lang.String)"MoreVars");
    //  --- [X | MoreVars]
    compound_3 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_2});
    //  --- VarToken
    var_4 = factory.makeVariable((java.lang.String)"VarToken");
    //  --- NewVars
    var_5 = factory.makeVariable((java.lang.String)"NewVars");
    //  --- [X | NewVars]
    compound_6 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_5});
    //  --- make_unique_variable_token(Name, [X | MoreVars], VarToken, [X | NewVars])
    compound_7 = factory.makeCompoundTerm((java.lang.String)"make_unique_variable_token", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, compound_3, var_4, compound_6});
    //  --- make_unique_variable_token(Name, MoreVars, VarToken, NewVars)
    compound_8 = factory.makeCompoundTerm((java.lang.String)"make_unique_variable_token", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_2, var_4, var_5});
    //  --- ':-'(make_unique_variable_token(Name, [X | MoreVars], VarToken, [X | NewVars]), make_unique_variable_token(Name, MoreVars, VarToken, NewVars))
    compound_9 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_7, compound_8});
    return compound_9;
  }
  
}
