package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:25 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.operator_no_comma_1
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.operator_no_comma_1 ()
  {
  }
  
  public int getArity ()
  {
    return 1;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_1;
    com.svincent.moksa.CompoundTerm compound_0;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg ,
    //  --- ,
    compound_0 = factory.makeAtom((java.lang.String)",");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)compound_0))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- !
    compound_1 = factory.makeAtom((java.lang.String)"!");
    //  --- fail
    compound_2 = factory.makeAtom((java.lang.String)"fail");
    //  --- ','(!, fail)
    compound_3 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_1, compound_2});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_3, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "operator_no_comma/1";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_1;
    com.svincent.moksa.CompoundTerm compound_0;
    //  --- ,
    compound_0 = factory.makeAtom((java.lang.String)",");
    //  --- operator_no_comma(,)
    compound_1 = factory.makeCompoundTerm((java.lang.String)"operator_no_comma", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0});
    //  --- !
    compound_2 = factory.makeAtom((java.lang.String)"!");
    //  --- fail
    compound_3 = factory.makeAtom((java.lang.String)"fail");
    //  --- ','(!, fail)
    compound_4 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, compound_3});
    //  --- ':-'(operator_no_comma(,), ','(!, fail))
    compound_5 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_1, compound_4});
    return compound_5;
  }
  
}
