package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:24 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt15
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt15 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.CompoundTerm compound_0;
    com.svincent.moksa.CompoundTerm compound_11;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.Variable var_8;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.WamInteger int_6;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg [open_list | ListTokens]
    //  --- open_list
    compound_0 = factory.makeAtom((java.lang.String)"open_list");
    //  --- ListTokens
    var_1 = factory.makeVariable((java.lang.String)"ListTokens");
    //  --- [open_list | ListTokens]
    compound_2 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, var_1});
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)compound_2))
      return wam.Fail;
    //  *** test arg Priority
    //  --- Priority
    var_3 = factory.makeVariable((java.lang.String)"Priority");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_3))
      return wam.Fail;
    //  *** test arg Term
    //  --- Term
    var_4 = factory.makeVariable((java.lang.String)"Term");
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)var_4))
      return wam.Fail;
    //  *** test arg Rest
    //  --- Rest
    var_5 = factory.makeVariable((java.lang.String)"Rest");
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_5))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- 0
    int_6 = factory.makeInteger((int)0);
    //  --- '>='(Priority, 0)
    compound_7 = factory.makeCompoundTerm((java.lang.String)">=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_3, int_6});
    //  --- List
    var_8 = factory.makeVariable((java.lang.String)"List");
    //  --- parse_prolog_term_list(ListTokens, Priority, List, Rest)
    compound_9 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_3, var_8, var_5});
    //  --- '='(Term, List)
    compound_10 = factory.makeCompoundTerm((java.lang.String)"=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_4, var_8});
    //  --- ','(parse_prolog_term_list(ListTokens, Priority, List, Rest), '='(Term, List))
    compound_11 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_9, compound_10});
    //  --- ','('>='(Priority, 0), ','(parse_prolog_term_list(ListTokens, Priority, List, Rest), '='(Term, List)))
    compound_12 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_7, compound_11});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_12, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "parse_prolog_term/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.CompoundTerm compound_8;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.CompoundTerm compound_14;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_13;
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.CompoundTerm compound_0;
    com.svincent.moksa.CompoundTerm compound_11;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.Variable var_9;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.WamInteger int_7;
    com.svincent.moksa.Variable var_3;
    //  --- open_list
    compound_0 = factory.makeAtom((java.lang.String)"open_list");
    //  --- ListTokens
    var_1 = factory.makeVariable((java.lang.String)"ListTokens");
    //  --- [open_list | ListTokens]
    compound_2 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, var_1});
    //  --- Priority
    var_3 = factory.makeVariable((java.lang.String)"Priority");
    //  --- Term
    var_4 = factory.makeVariable((java.lang.String)"Term");
    //  --- Rest
    var_5 = factory.makeVariable((java.lang.String)"Rest");
    //  --- parse_prolog_term([open_list | ListTokens], Priority, Term, Rest)
    compound_6 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, var_3, var_4, var_5});
    //  --- 0
    int_7 = factory.makeInteger((int)0);
    //  --- '>='(Priority, 0)
    compound_8 = factory.makeCompoundTerm((java.lang.String)">=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_3, int_7});
    //  --- List
    var_9 = factory.makeVariable((java.lang.String)"List");
    //  --- parse_prolog_term_list(ListTokens, Priority, List, Rest)
    compound_10 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_3, var_9, var_5});
    //  --- '='(Term, List)
    compound_11 = factory.makeCompoundTerm((java.lang.String)"=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_4, var_9});
    //  --- ','(parse_prolog_term_list(ListTokens, Priority, List, Rest), '='(Term, List))
    compound_12 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_10, compound_11});
    //  --- ','('>='(Priority, 0), ','(parse_prolog_term_list(ListTokens, Priority, List, Rest), '='(Term, List)))
    compound_13 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_8, compound_12});
    //  --- ':-'(parse_prolog_term([open_list | ListTokens], Priority, Term, Rest), ','('>='(Priority, 0), ','(parse_prolog_term_list(ListTokens, Priority, List, Rest), '='(Term, List))))
    compound_14 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_6, compound_13});
    return compound_14;
  }
  
}
