package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:25 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_list_4
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.parse_prolog_more_list_4 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_0;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.Variable var_3;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg [close_list | Rest]
    //  --- close_list
    compound_0 = factory.makeAtom((java.lang.String)"close_list");
    //  --- Rest
    var_1 = factory.makeVariable((java.lang.String)"Rest");
    //  --- [close_list | Rest]
    compound_2 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, var_1});
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)compound_2))
      return wam.Fail;
    //  *** test arg Priority
    //  --- Priority
    var_3 = factory.makeVariable((java.lang.String)"Priority");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_3))
      return wam.Fail;
    //  *** test arg []
    //  --- []
    compound_4 = factory.makeAtom((java.lang.String)"[]");
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)compound_4))
      return wam.Fail;
    //  *** test arg Rest
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    continuation = wam.getContinuation();
    return continuation;
  }
  
  public java.lang.String getName ()
  {
    return "parse_prolog_more_list/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_0;
    //  --- close_list
    compound_0 = factory.makeAtom((java.lang.String)"close_list");
    //  --- Rest
    var_1 = factory.makeVariable((java.lang.String)"Rest");
    //  --- [close_list | Rest]
    compound_2 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, var_1});
    //  --- Priority
    var_3 = factory.makeVariable((java.lang.String)"Priority");
    //  --- []
    compound_4 = factory.makeAtom((java.lang.String)"[]");
    //  --- parse_prolog_more_list([close_list | Rest], Priority, [], Rest)
    compound_5 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_more_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, var_3, compound_4, var_1});
    return compound_5;
  }
  
}
