package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:19 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt5
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt5 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.WamInteger int_9;
    com.svincent.moksa.Variable var_8;
    com.svincent.moksa.Variable var_7;
    com.svincent.moksa.Variable var_6;
    com.svincent.moksa.Variable var_11;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_1;
    com.svincent.moksa.CompoundTerm compound_16;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.CompoundTerm compound_15;
    com.svincent.moksa.CompoundTerm compound_14;
    com.svincent.moksa.CompoundTerm compound_13;
    com.svincent.moksa.Continuation continuation;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg [name(Name), open | Rest]
    //  --- Name
    var_0 = factory.makeVariable((java.lang.String)"Name");
    //  --- name(Name)
    compound_1 = factory.makeCompoundTerm((java.lang.String)"name", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0});
    //  --- open
    compound_2 = factory.makeAtom((java.lang.String)"open");
    //  --- Rest
    var_3 = factory.makeVariable((java.lang.String)"Rest");
    //  --- [open | Rest]
    compound_4 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, var_3});
    //  --- [name(Name), open | Rest]
    compound_5 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_1, compound_4});
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)compound_5))
      return wam.Fail;
    //  *** test arg Priority
    //  --- Priority
    var_6 = factory.makeVariable((java.lang.String)"Priority");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_6))
      return wam.Fail;
    //  *** test arg Term
    //  --- Term
    var_7 = factory.makeVariable((java.lang.String)"Term");
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)var_7))
      return wam.Fail;
    //  *** test arg Tail
    //  --- Tail
    var_8 = factory.makeVariable((java.lang.String)"Tail");
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_8))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- 0
    int_9 = factory.makeInteger((int)0);
    //  --- '>='(Priority, 0)
    compound_10 = factory.makeCompoundTerm((java.lang.String)">=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_6, int_9});
    //  --- Args
    var_11 = factory.makeVariable((java.lang.String)"Args");
    //  --- parse_prolog_arg_list(Rest, Priority, Args, Tail)
    compound_12 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_arg_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_3, var_6, var_11, var_8});
    //  --- [Name | Args]
    compound_13 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_11});
    //  --- '=..'(Term, [Name | Args])
    compound_14 = factory.makeCompoundTerm((java.lang.String)"=..", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_7, compound_13});
    //  --- ','(parse_prolog_arg_list(Rest, Priority, Args, Tail), '=..'(Term, [Name | Args]))
    compound_15 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_12, compound_14});
    //  --- ','('>='(Priority, 0), ','(parse_prolog_arg_list(Rest, Priority, Args, Tail), '=..'(Term, [Name | Args])))
    compound_16 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_10, compound_15});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_16, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "parse_prolog_term/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.CompoundTerm compound_11;
    com.svincent.moksa.WamInteger int_10;
    com.svincent.moksa.Variable var_8;
    com.svincent.moksa.Variable var_7;
    com.svincent.moksa.Variable var_6;
    com.svincent.moksa.Variable var_12;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_18;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_17;
    com.svincent.moksa.CompoundTerm compound_1;
    com.svincent.moksa.CompoundTerm compound_16;
    com.svincent.moksa.CompoundTerm compound_15;
    com.svincent.moksa.CompoundTerm compound_14;
    com.svincent.moksa.CompoundTerm compound_13;
    //  --- Name
    var_0 = factory.makeVariable((java.lang.String)"Name");
    //  --- name(Name)
    compound_1 = factory.makeCompoundTerm((java.lang.String)"name", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0});
    //  --- open
    compound_2 = factory.makeAtom((java.lang.String)"open");
    //  --- Rest
    var_3 = factory.makeVariable((java.lang.String)"Rest");
    //  --- [open | Rest]
    compound_4 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, var_3});
    //  --- [name(Name), open | Rest]
    compound_5 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_1, compound_4});
    //  --- Priority
    var_6 = factory.makeVariable((java.lang.String)"Priority");
    //  --- Term
    var_7 = factory.makeVariable((java.lang.String)"Term");
    //  --- Tail
    var_8 = factory.makeVariable((java.lang.String)"Tail");
    //  --- parse_prolog_term([name(Name), open | Rest], Priority, Term, Tail)
    compound_9 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_5, var_6, var_7, var_8});
    //  --- 0
    int_10 = factory.makeInteger((int)0);
    //  --- '>='(Priority, 0)
    compound_11 = factory.makeCompoundTerm((java.lang.String)">=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_6, int_10});
    //  --- Args
    var_12 = factory.makeVariable((java.lang.String)"Args");
    //  --- parse_prolog_arg_list(Rest, Priority, Args, Tail)
    compound_13 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_arg_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_3, var_6, var_12, var_8});
    //  --- [Name | Args]
    compound_14 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_12});
    //  --- '=..'(Term, [Name | Args])
    compound_15 = factory.makeCompoundTerm((java.lang.String)"=..", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_7, compound_14});
    //  --- ','(parse_prolog_arg_list(Rest, Priority, Args, Tail), '=..'(Term, [Name | Args]))
    compound_16 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_13, compound_15});
    //  --- ','('>='(Priority, 0), ','(parse_prolog_arg_list(Rest, Priority, Args, Tail), '=..'(Term, [Name | Args])))
    compound_17 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_11, compound_16});
    //  --- ':-'(parse_prolog_term([name(Name), open | Rest], Priority, Term, Tail), ','('>='(Priority, 0), ','(parse_prolog_arg_list(Rest, Priority, Args, Tail), '=..'(Term, [Name | Args]))))
    compound_18 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_9, compound_17});
    return compound_18;
  }
  
}
