package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:21 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt12
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_4_alt12 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.CompoundTerm compound_29;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.CompoundTerm compound_28;
    com.svincent.moksa.CompoundTerm compound_27;
    com.svincent.moksa.CompoundTerm compound_26;
    com.svincent.moksa.CompoundTerm compound_25;
    com.svincent.moksa.CompoundTerm compound_24;
    com.svincent.moksa.CompoundTerm compound_22;
    com.svincent.moksa.CompoundTerm compound_21;
    com.svincent.moksa.Variable var_23;
    com.svincent.moksa.Variable var_20;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.CompoundTerm compound_19;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_16;
    com.svincent.moksa.CompoundTerm compound_15;
    com.svincent.moksa.Variable var_18;
    com.svincent.moksa.Variable var_17;
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.CompoundTerm compound_11;
    com.svincent.moksa.Variable var_14;
    com.svincent.moksa.Variable var_13;
    com.svincent.moksa.Variable var_10;
    com.svincent.moksa.Variable var_7;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_2;
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_36;
    com.svincent.moksa.CompoundTerm compound_35;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_34;
    com.svincent.moksa.CompoundTerm compound_8;
    com.svincent.moksa.CompoundTerm compound_33;
    com.svincent.moksa.CompoundTerm compound_32;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.CompoundTerm compound_31;
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_30;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg Tokens
    //  --- Tokens
    var_0 = factory.makeVariable((java.lang.String)"Tokens");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)var_0))
      return wam.Fail;
    //  *** test arg Priority
    //  --- Priority
    var_1 = factory.makeVariable((java.lang.String)"Priority");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    //  *** test arg Term
    //  --- Term
    var_2 = factory.makeVariable((java.lang.String)"Term");
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)var_2))
      return wam.Fail;
    //  *** test arg Rest
    //  --- Rest
    var_3 = factory.makeVariable((java.lang.String)"Rest");
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_3))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- ATokens
    var_4 = factory.makeVariable((java.lang.String)"ATokens");
    //  --- ,
    compound_5 = factory.makeAtom((java.lang.String)",");
    //  --- name(,)
    compound_6 = factory.makeCompoundTerm((java.lang.String)"name", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_5});
    //  --- BTokens
    var_7 = factory.makeVariable((java.lang.String)"BTokens");
    //  --- [name(,) | BTokens]
    compound_8 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_6, var_7});
    //  --- append(ATokens, [name(,) | BTokens], Tokens)
    compound_9 = factory.makeCompoundTerm((java.lang.String)"append", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_4, compound_8, var_0});
    //  --- Op
    var_10 = factory.makeVariable((java.lang.String)"Op");
    //  --- ,
    compound_11 = factory.makeAtom((java.lang.String)",");
    //  --- '='(Op, ,)
    compound_12 = factory.makeCompoundTerm((java.lang.String)"=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_10, compound_11});
    //  --- OPri
    var_13 = factory.makeVariable((java.lang.String)"OPri");
    //  --- Op_Specifier
    var_14 = factory.makeVariable((java.lang.String)"Op_Specifier");
    //  --- current_op(OPri, Op_Specifier, Op)
    compound_15 = factory.makeCompoundTerm((java.lang.String)"current_op", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_13, var_14, var_10});
    //  --- '>='(Priority, OPri)
    compound_16 = factory.makeCompoundTerm((java.lang.String)">=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_13});
    //  --- APri
    var_17 = factory.makeVariable((java.lang.String)"APri");
    //  --- BPri
    var_18 = factory.makeVariable((java.lang.String)"BPri");
    //  --- calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri)
    compound_19 = factory.makeCompoundTerm((java.lang.String)"calculate_prolog_infix_subpriority", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_14, var_13, var_17, var_18});
    //  --- A
    var_20 = factory.makeVariable((java.lang.String)"A");
    //  --- []
    compound_21 = factory.makeAtom((java.lang.String)"[]");
    //  --- parse_prolog_term(ATokens, APri, A, [])
    compound_22 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_4, var_17, var_20, compound_21});
    //  --- B
    var_23 = factory.makeVariable((java.lang.String)"B");
    //  --- parse_prolog_term(BTokens, BPri, B, Rest)
    compound_24 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_7, var_18, var_23, var_3});
    //  --- []
    compound_25 = factory.makeAtom((java.lang.String)"[]");
    //  --- [B]
    compound_26 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_23, compound_25});
    //  --- [A, B]
    compound_27 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_20, compound_26});
    //  --- [Op, A, B]
    compound_28 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_10, compound_27});
    //  --- '=..'(Term, [Op, A, B])
    compound_29 = factory.makeCompoundTerm((java.lang.String)"=..", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_2, compound_28});
    //  --- ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))
    compound_30 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_24, compound_29});
    //  --- ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))
    compound_31 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_22, compound_30});
    //  --- ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))))
    compound_32 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_19, compound_31});
    //  --- ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))))
    compound_33 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_16, compound_32});
    //  --- ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))))))
    compound_34 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_15, compound_33});
    //  --- ','('='(Op, ,), ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))))))
    compound_35 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_12, compound_34});
    //  --- ','(append(ATokens, [name(,) | BTokens], Tokens), ','('='(Op, ,), ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))))))))
    compound_36 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_9, compound_35});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_36, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "parse_prolog_term/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.CompoundTerm compound_29;
    com.svincent.moksa.CompoundTerm compound_28;
    com.svincent.moksa.CompoundTerm compound_27;
    com.svincent.moksa.CompoundTerm compound_26;
    com.svincent.moksa.CompoundTerm compound_25;
    com.svincent.moksa.CompoundTerm compound_23;
    com.svincent.moksa.CompoundTerm compound_22;
    com.svincent.moksa.CompoundTerm compound_20;
    com.svincent.moksa.Variable var_24;
    com.svincent.moksa.Variable var_21;
    com.svincent.moksa.CompoundTerm compound_17;
    com.svincent.moksa.CompoundTerm compound_16;
    com.svincent.moksa.Variable var_19;
    com.svincent.moksa.CompoundTerm compound_13;
    com.svincent.moksa.Variable var_18;
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.Variable var_15;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.Variable var_14;
    com.svincent.moksa.Variable var_11;
    com.svincent.moksa.Variable var_8;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_2;
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_38;
    com.svincent.moksa.CompoundTerm compound_37;
    com.svincent.moksa.CompoundTerm compound_36;
    com.svincent.moksa.CompoundTerm compound_35;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_34;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.CompoundTerm compound_33;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.CompoundTerm compound_32;
    com.svincent.moksa.CompoundTerm compound_31;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_30;
    //  --- Tokens
    var_0 = factory.makeVariable((java.lang.String)"Tokens");
    //  --- Priority
    var_1 = factory.makeVariable((java.lang.String)"Priority");
    //  --- Term
    var_2 = factory.makeVariable((java.lang.String)"Term");
    //  --- Rest
    var_3 = factory.makeVariable((java.lang.String)"Rest");
    //  --- parse_prolog_term(Tokens, Priority, Term, Rest)
    compound_4 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_1, var_2, var_3});
    //  --- ATokens
    var_5 = factory.makeVariable((java.lang.String)"ATokens");
    //  --- ,
    compound_6 = factory.makeAtom((java.lang.String)",");
    //  --- name(,)
    compound_7 = factory.makeCompoundTerm((java.lang.String)"name", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_6});
    //  --- BTokens
    var_8 = factory.makeVariable((java.lang.String)"BTokens");
    //  --- [name(,) | BTokens]
    compound_9 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_7, var_8});
    //  --- append(ATokens, [name(,) | BTokens], Tokens)
    compound_10 = factory.makeCompoundTerm((java.lang.String)"append", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_5, compound_9, var_0});
    //  --- Op
    var_11 = factory.makeVariable((java.lang.String)"Op");
    //  --- ,
    compound_12 = factory.makeAtom((java.lang.String)",");
    //  --- '='(Op, ,)
    compound_13 = factory.makeCompoundTerm((java.lang.String)"=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_11, compound_12});
    //  --- OPri
    var_14 = factory.makeVariable((java.lang.String)"OPri");
    //  --- Op_Specifier
    var_15 = factory.makeVariable((java.lang.String)"Op_Specifier");
    //  --- current_op(OPri, Op_Specifier, Op)
    compound_16 = factory.makeCompoundTerm((java.lang.String)"current_op", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_14, var_15, var_11});
    //  --- '>='(Priority, OPri)
    compound_17 = factory.makeCompoundTerm((java.lang.String)">=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_14});
    //  --- APri
    var_18 = factory.makeVariable((java.lang.String)"APri");
    //  --- BPri
    var_19 = factory.makeVariable((java.lang.String)"BPri");
    //  --- calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri)
    compound_20 = factory.makeCompoundTerm((java.lang.String)"calculate_prolog_infix_subpriority", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_15, var_14, var_18, var_19});
    //  --- A
    var_21 = factory.makeVariable((java.lang.String)"A");
    //  --- []
    compound_22 = factory.makeAtom((java.lang.String)"[]");
    //  --- parse_prolog_term(ATokens, APri, A, [])
    compound_23 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_5, var_18, var_21, compound_22});
    //  --- B
    var_24 = factory.makeVariable((java.lang.String)"B");
    //  --- parse_prolog_term(BTokens, BPri, B, Rest)
    compound_25 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_8, var_19, var_24, var_3});
    //  --- []
    compound_26 = factory.makeAtom((java.lang.String)"[]");
    //  --- [B]
    compound_27 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_24, compound_26});
    //  --- [A, B]
    compound_28 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_21, compound_27});
    //  --- [Op, A, B]
    compound_29 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_11, compound_28});
    //  --- '=..'(Term, [Op, A, B])
    compound_30 = factory.makeCompoundTerm((java.lang.String)"=..", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_2, compound_29});
    //  --- ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))
    compound_31 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_25, compound_30});
    //  --- ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))
    compound_32 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_23, compound_31});
    //  --- ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))))
    compound_33 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_20, compound_32});
    //  --- ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))))
    compound_34 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_17, compound_33});
    //  --- ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))))))
    compound_35 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_16, compound_34});
    //  --- ','('='(Op, ,), ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))))))
    compound_36 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_13, compound_35});
    //  --- ','(append(ATokens, [name(,) | BTokens], Tokens), ','('='(Op, ,), ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B]))))))))
    compound_37 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_10, compound_36});
    //  --- ':-'(parse_prolog_term(Tokens, Priority, Term, Rest), ','(append(ATokens, [name(,) | BTokens], Tokens), ','('='(Op, ,), ','(current_op(OPri, Op_Specifier, Op), ','('>='(Priority, OPri), ','(calculate_prolog_infix_subpriority(Op_Specifier, OPri, APri, BPri), ','(parse_prolog_term(ATokens, APri, A, []), ','(parse_prolog_term(BTokens, BPri, B, Rest), '=..'(Term, [Op, A, B])))))))))
    compound_38 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_4, compound_37});
    return compound_38;
  }
  
}
