package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:25 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_list_4
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.parse_prolog_term_list_4 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_8;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.CompoundTerm compound_11;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.Variable var_7;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_2;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg Tokens
    //  --- Tokens
    var_0 = factory.makeVariable((java.lang.String)"Tokens");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)var_0))
      return wam.Fail;
    //  *** test arg Priority
    //  --- Priority
    var_1 = factory.makeVariable((java.lang.String)"Priority");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    //  *** test arg List
    //  --- List
    var_2 = factory.makeVariable((java.lang.String)"List");
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)var_2))
      return wam.Fail;
    //  *** test arg Tail
    //  --- Tail
    var_3 = factory.makeVariable((java.lang.String)"Tail");
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_3))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- Exp
    var_4 = factory.makeVariable((java.lang.String)"Exp");
    //  --- MoreListTokens
    var_5 = factory.makeVariable((java.lang.String)"MoreListTokens");
    //  --- parse_prolog_exp(Tokens, Priority, Exp, MoreListTokens)
    compound_6 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_exp", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_1, var_4, var_5});
    //  --- MoreList
    var_7 = factory.makeVariable((java.lang.String)"MoreList");
    //  --- parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail)
    compound_8 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_more_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_5, var_1, var_7, var_3});
    //  --- [Exp | MoreList]
    compound_9 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_4, var_7});
    //  --- '='(List, [Exp | MoreList])
    compound_10 = factory.makeCompoundTerm((java.lang.String)"=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_2, compound_9});
    //  --- ','(parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail), '='(List, [Exp | MoreList]))
    compound_11 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_8, compound_10});
    //  --- ','(parse_prolog_exp(Tokens, Priority, Exp, MoreListTokens), ','(parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail), '='(List, [Exp | MoreList])))
    compound_12 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_6, compound_11});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_12, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "parse_prolog_term_list/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_14;
    com.svincent.moksa.CompoundTerm compound_13;
    com.svincent.moksa.CompoundTerm compound_12;
    com.svincent.moksa.CompoundTerm compound_11;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.Variable var_8;
    com.svincent.moksa.Variable var_6;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_3;
    com.svincent.moksa.Variable var_2;
    //  --- Tokens
    var_0 = factory.makeVariable((java.lang.String)"Tokens");
    //  --- Priority
    var_1 = factory.makeVariable((java.lang.String)"Priority");
    //  --- List
    var_2 = factory.makeVariable((java.lang.String)"List");
    //  --- Tail
    var_3 = factory.makeVariable((java.lang.String)"Tail");
    //  --- parse_prolog_term_list(Tokens, Priority, List, Tail)
    compound_4 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_term_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_1, var_2, var_3});
    //  --- Exp
    var_5 = factory.makeVariable((java.lang.String)"Exp");
    //  --- MoreListTokens
    var_6 = factory.makeVariable((java.lang.String)"MoreListTokens");
    //  --- parse_prolog_exp(Tokens, Priority, Exp, MoreListTokens)
    compound_7 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_exp", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_1, var_5, var_6});
    //  --- MoreList
    var_8 = factory.makeVariable((java.lang.String)"MoreList");
    //  --- parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail)
    compound_9 = factory.makeCompoundTerm((java.lang.String)"parse_prolog_more_list", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_6, var_1, var_8, var_3});
    //  --- [Exp | MoreList]
    compound_10 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_5, var_8});
    //  --- '='(List, [Exp | MoreList])
    compound_11 = factory.makeCompoundTerm((java.lang.String)"=", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_2, compound_10});
    //  --- ','(parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail), '='(List, [Exp | MoreList]))
    compound_12 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_9, compound_11});
    //  --- ','(parse_prolog_exp(Tokens, Priority, Exp, MoreListTokens), ','(parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail), '='(List, [Exp | MoreList])))
    compound_13 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_7, compound_12});
    //  --- ':-'(parse_prolog_term_list(Tokens, Priority, List, Tail), ','(parse_prolog_exp(Tokens, Priority, Exp, MoreListTokens), ','(parse_prolog_more_list(MoreListTokens, Priority, MoreList, Tail), '='(List, [Exp | MoreList]))))
    compound_14 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_4, compound_13});
    return compound_14;
  }
  
}
