package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:17 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4_alt3
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4_alt3 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_8;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_2;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg T
    //  --- T
    var_0 = factory.makeVariable((java.lang.String)"T");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)var_0))
      return wam.Fail;
    //  *** test arg S
    //  --- S
    var_1 = factory.makeVariable((java.lang.String)"S");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    //  *** test arg [T | Rest]
    //  --- Rest
    var_2 = factory.makeVariable((java.lang.String)"Rest");
    //  --- [T | Rest]
    compound_3 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_2});
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)compound_3))
      return wam.Fail;
    //  *** test arg Vars
    //  --- Vars
    var_4 = factory.makeVariable((java.lang.String)"Vars");
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_4))
      return wam.Fail;
    continuation = wam.getContinuation();
    //  --- NextToken
    var_5 = factory.makeVariable((java.lang.String)"NextToken");
    //  --- get_prolog_token(S, NextToken)
    compound_6 = factory.makeCompoundTerm((java.lang.String)"get_prolog_token", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_5});
    //  --- prolog_term_to_tokens(NextToken, S, Rest, Vars)
    compound_7 = factory.makeCompoundTerm((java.lang.String)"prolog_term_to_tokens", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_5, var_1, var_2, var_4});
    //  --- ','(get_prolog_token(S, NextToken), prolog_term_to_tokens(NextToken, S, Rest, Vars))
    compound_8 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_6, compound_7});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_8, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "prolog_term_to_tokens/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.CompoundTerm compound_9;
    com.svincent.moksa.CompoundTerm compound_8;
    com.svincent.moksa.CompoundTerm compound_7;
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_10;
    com.svincent.moksa.Variable var_6;
    com.svincent.moksa.Variable var_4;
    com.svincent.moksa.Variable var_2;
    //  --- T
    var_0 = factory.makeVariable((java.lang.String)"T");
    //  --- S
    var_1 = factory.makeVariable((java.lang.String)"S");
    //  --- Rest
    var_2 = factory.makeVariable((java.lang.String)"Rest");
    //  --- [T | Rest]
    compound_3 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_2});
    //  --- Vars
    var_4 = factory.makeVariable((java.lang.String)"Vars");
    //  --- prolog_term_to_tokens(T, S, [T | Rest], Vars)
    compound_5 = factory.makeCompoundTerm((java.lang.String)"prolog_term_to_tokens", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0, var_1, compound_3, var_4});
    //  --- NextToken
    var_6 = factory.makeVariable((java.lang.String)"NextToken");
    //  --- get_prolog_token(S, NextToken)
    compound_7 = factory.makeCompoundTerm((java.lang.String)"get_prolog_token", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1, var_6});
    //  --- prolog_term_to_tokens(NextToken, S, Rest, Vars)
    compound_8 = factory.makeCompoundTerm((java.lang.String)"prolog_term_to_tokens", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_6, var_1, var_2, var_4});
    //  --- ','(get_prolog_token(S, NextToken), prolog_term_to_tokens(NextToken, S, Rest, Vars))
    compound_9 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_7, compound_8});
    //  --- ':-'(prolog_term_to_tokens(T, S, [T | Rest], Vars), ','(get_prolog_token(S, NextToken), prolog_term_to_tokens(NextToken, S, Rest, Vars)))
    compound_10 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_5, compound_9});
    return compound_10;
  }
  
}
