package com.svincent.moksa.prolog.parser_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:16 AM EST
 */
public class com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.parser_prolog.prolog_term_to_tokens_4 ()
  {
  }
  
  public int getArity ()
  {
    return 4;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_0;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.Variable var_5;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg end
    //  --- end
    compound_0 = factory.makeAtom((java.lang.String)"end");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)compound_0))
      return wam.Fail;
    //  *** test arg S
    //  --- S
    var_1 = factory.makeVariable((java.lang.String)"S");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    //  *** test arg [end]
    //  --- end
    compound_2 = factory.makeAtom((java.lang.String)"end");
    //  --- []
    compound_3 = factory.makeAtom((java.lang.String)"[]");
    //  --- [end]
    compound_4 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, compound_3});
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)compound_4))
      return wam.Fail;
    //  *** test arg Vars
    //  --- Vars
    var_5 = factory.makeVariable((java.lang.String)"Vars");
    if (wam.badparm((int)3, (com.svincent.moksa.PrologTerm)var_5))
      return wam.Fail;
    continuation = wam.getContinuation();
    return continuation;
  }
  
  public java.lang.String getName ()
  {
    return "prolog_term_to_tokens/4";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.CompoundTerm compound_6;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.Variable var_5;
    com.svincent.moksa.CompoundTerm compound_0;
    //  --- end
    compound_0 = factory.makeAtom((java.lang.String)"end");
    //  --- S
    var_1 = factory.makeVariable((java.lang.String)"S");
    //  --- end
    compound_2 = factory.makeAtom((java.lang.String)"end");
    //  --- []
    compound_3 = factory.makeAtom((java.lang.String)"[]");
    //  --- [end]
    compound_4 = factory.makeCompoundTerm((java.lang.String)".", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, compound_3});
    //  --- Vars
    var_5 = factory.makeVariable((java.lang.String)"Vars");
    //  --- prolog_term_to_tokens(end, S, [end], Vars)
    compound_6 = factory.makeCompoundTerm((java.lang.String)"prolog_term_to_tokens", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, var_1, compound_4, var_5});
    return compound_6;
  }
  
}
