package com.svincent.moksa.prolog.system_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:07:00 AM EST
 */
public class com.svincent.moksa.prolog.system_prolog.append_3
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.system_prolog.append_3 ()
  {
  }
  
  public int getArity ()
  {
    return 3;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.CompoundTerm compound_0;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg []
    //  --- []
    compound_0 = factory.makeAtom((java.lang.String)"[]");
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)compound_0))
      return wam.Fail;
    //  *** test arg L
    //  --- L
    var_1 = factory.makeVariable((java.lang.String)"L");
    if (wam.badparm((int)1, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    //  *** test arg L
    if (wam.badparm((int)2, (com.svincent.moksa.PrologTerm)var_1))
      return wam.Fail;
    continuation = wam.getContinuation();
    return continuation;
  }
  
  public java.lang.String getName ()
  {
    return "append/3";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_0;
    //  --- []
    compound_0 = factory.makeAtom((java.lang.String)"[]");
    //  --- L
    var_1 = factory.makeVariable((java.lang.String)"L");
    //  --- append([], L, L)
    compound_2 = factory.makeCompoundTerm((java.lang.String)"append", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, var_1, var_1});
    return compound_2;
  }
  
}
