package com.svincent.moksa.prolog.system_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 8:06:59 AM EST
 */
public class com.svincent.moksa.prolog.system_prolog.flush_output_0
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.system_prolog.flush_output_0 ()
  {
  }
  
  public int getArity ()
  {
    return 0;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.Variable var_0;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_1;
    engine = wam.getEngine();
    factory = engine.getFactory();
    continuation = wam.getContinuation();
    //  --- S
    var_0 = factory.makeVariable((java.lang.String)"S");
    //  --- current_output(S)
    compound_1 = factory.makeCompoundTerm((java.lang.String)"current_output", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0});
    //  --- flush_output(S)
    compound_2 = factory.makeCompoundTerm((java.lang.String)"flush_output", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_0});
    //  --- ','(current_output(S), flush_output(S))
    compound_3 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_1, compound_2});
    return com.svincent.moksa.Continuation.make((com.svincent.moksa.PrologEngine)engine, (com.svincent.moksa.PrologTerm)compound_3, (com.svincent.moksa.Continuation)continuation);
  }
  
  public java.lang.String getName ()
  {
    return "flush_output/0";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.Variable var_1;
    com.svincent.moksa.CompoundTerm compound_5;
    com.svincent.moksa.CompoundTerm compound_4;
    com.svincent.moksa.CompoundTerm compound_3;
    com.svincent.moksa.CompoundTerm compound_2;
    com.svincent.moksa.CompoundTerm compound_0;
    //  --- flush_output
    compound_0 = factory.makeAtom((java.lang.String)"flush_output");
    //  --- S
    var_1 = factory.makeVariable((java.lang.String)"S");
    //  --- current_output(S)
    compound_2 = factory.makeCompoundTerm((java.lang.String)"current_output", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1});
    //  --- flush_output(S)
    compound_3 = factory.makeCompoundTerm((java.lang.String)"flush_output", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {var_1});
    //  --- ','(current_output(S), flush_output(S))
    compound_4 = factory.makeCompoundTerm((java.lang.String)",", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_2, compound_3});
    //  --- ':-'(flush_output, ','(current_output(S), flush_output(S)))
    compound_5 = factory.makeCompoundTerm((java.lang.String)":-", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {compound_0, compound_4});
    return compound_5;
  }
  
}
