package com.svincent.moksa.prolog.small_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 6:56:31 PM EST
 */
public class com.svincent.moksa.prolog.small_prolog.helloWorld_1
  extends com.svincent.moksa.CompiledRule
{
  public com.svincent.moksa.prolog.small_prolog.helloWorld_1 ()
  {
    super ();
    return;
  }
  
  public int getArity ()
  {
    return 1;
  }
  
  public com.svincent.moksa.Continuation invokeRule (com.svincent.moksa.Wam wam)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.Continuation continuation;
    com.svincent.moksa.PrologFactory factory;
    com.svincent.moksa.PrologEngine engine;
    com.svincent.moksa.WamInteger int_0;
    engine = wam.getEngine();
    factory = engine.getFactory();
    //  *** test arg 3
    //  --- 3
    int_0 = factory.makeInteger((int)3);
    if (wam.badparm((int)0, (com.svincent.moksa.PrologTerm)int_0))
      return wam.Fail;
    continuation = wam.getContinuation();
    return continuation;
  }
  
  public java.lang.String getName ()
  {
    return "helloWorld/1";
  }
  
  public com.svincent.moksa.PrologTerm makeTerm (com.svincent.moksa.PrologFactory factory)
  {
    com.svincent.moksa.CompoundTerm compound_1;
    com.svincent.moksa.WamInteger int_0;
    //  --- 3
    int_0 = factory.makeInteger((int)3);
    //  --- helloWorld(3)
    compound_1 = factory.makeCompoundTerm((java.lang.String)"helloWorld", (com.svincent.moksa.PrologTerm[])new com.svincent.moksa.PrologTerm[] {int_0});
    return compound_1;
  }
  
}
