package com.svincent.moksa.prolog.small_prolog;

/*
 * This file was automatically generated by Smalljava.
 * 
 * Smalljava Vnull-null
 * Copyright (C) 1999 Shawn Vincent
 * http://www.svincent.com/moksa/
 * Smalljava is released under the GNU general public license
 * See http://www.gnu.org/copyleft/gpl.html for details.
 * 
 * File generated: Thursday, December 2, 1999 6:56:31 PM EST
 */
public class com.svincent.moksa.prolog.small_prolog.Loader
  extends com.svincent.moksa.PrologLoader
{
  public com.svincent.moksa.prolog.small_prolog.Loader ()
  {
    super ();
    return;
  }
  
  public void load (com.svincent.moksa.PrologEngine engine)
    throws com.svincent.moksa.PrologException
  {
    com.svincent.moksa.PrologFactory factory;
    factory = engine.getFactory();
    engine.assertz((com.svincent.moksa.Rule)new com.svincent.moksa.prolog.small_prolog.helloWorld_1());
  }
  
}
